# config/database.yml

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: v_library_backend_development
  username: postgres
  password: "password" 
  host: localhost 

test:
  <<: *default
  database: v_library_backend_test
  username: postgres
  password: "password" 
  host: localhost

production:
  primary:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    schema_dump: db/schema.rb
  cache:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    schema_dump: db/cache_schema.rb
  queue:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    schema_dump: db/queue_schema.rb
  cable:
    <<: *default
    url: <%= ENV["DATABASE_URL"] %>
    schema_dump: db/cable_schema.rb